apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: go-app
    template:
        metadata:
            labels:
                app: go-app
        spec:
            containers:
                - name: go-app
                  image: jeshocarmel/ip_location_mapper
                  imagePullPolicy: Always
                  ports:
                    - containerPort: 8080
                  env:
                    - name: IPSTACK_API_KEY
                      valueFrom:
                        secretKeyRef:
                            name: app-secret
                            key: apikey
