version: '3.1'
services: 
    redis:
        image: "redis:alpine"    
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
         - "6379:6379"
        environment:
         - REDIS_REPLICATION_MODE=master
        container_name: ip_location_mapper_redis
    app:
        build: .
        image: jeshocarmel/ip_location_mapper
        depends_on: 
            - redis
        ports: 
            - "8080:8080"
        environment:
            REDIS_URL: redis:6379
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            IPSTACK_API_KEY: ${IPSTACK_API_KEY}
        container_name: ip_location_mapper